spring.application.name=ebookstore
spring.datasource.url=jdbc:postgresql://localhost:5432/ebookstore
spring.datasource.username=ebookuser
spring.datasource.password=ebook123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080