spring.application.name=ebookstore
server.port=${SERVER_PORT:8080}

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/ebookstore}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:ebookuser}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}

spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL:false}
spring.jpa.properties.hibernate.hbm2ddl.auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
