spring.application.name=ebookstore
spring.datasource.url=jdbc:postgresql://localhost:5432/ebookstore
spring.datasource.username=ebookuser
spring.datasource.password=ebook123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080

spring.jpa.properties.hibernate.hbm2ddl.auto=update
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.schema=DEBUG